const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const SIGN_UP_PERSON = "SIGN_UP_PERSON";
const UPLOAD_IMG = "UPLOAD_IMG";
const EDIT_MEMBER_INFO = "EDIT_MEMBER_INFO";

export { LOG_IN, LOG_OUT, SIGN_UP_PERSON, UPLOAD_IMG, EDIT_MEMBER_INFO };
